# Usa una imagen PHP con FPM
FROM php:8.0-fpm

# Instala extensiones de PHP si es necesario (ejemplo: mysqli)
RUN docker-php-ext-install mysqli

# Copia los archivos de tu aplicación al contenedor (opcional si ya usas volumes en docker-compose)
# COPY ./src /var/www/html
