version: '3.8'

services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./cliente:/var/www/html
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    container_name: php
    build: ./server/  # Asegúrate de tener un Dockerfile en esta carpeta
    volumes:
      - ./server/src:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: roo  # Si tienes un servicio de MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
